In [7]:
import json
import numpy as np
import pandas as pd

In [8]:
with open("out-export-v2.json", "r") as f:
    result = json.load(f)

scheduled_aks = result["scheduled_aks"]
inputs = result["input"]

results = []

for ak in scheduled_aks:
    ak_id = ak["ak_id"]
    room_id = ak["room_id"]
    timeslot_ids = ak["timeslot_ids"]

    timeslot_names = []
    for timeslot_id in timeslot_ids:
        for block in inputs["timeslots"]["blocks"]:
            for timeslot in block:
                if timeslot["id"] == timeslot_id:
                    timeslot_names.append(timeslot["info"]["start"])
                    break
            else:
                continue
            break

    timeslot_names = "/".join(sorted(timeslot_names))
    
    for room in inputs["rooms"]:
        if room["id"] == room_id:
            room_name = room["id"]
            break
    
    # print(ak_id, sorted([t["id"] for t in inputs["aks"]]))
    for ak in inputs["aks"]:
        if ak["id"] == ak_id:
            ak_name = ak["info"]["name"]
            break

    results.append((ak_name, room_name, timeslot_names))

In [9]:
print("| Timeslot | Raum | AK-Name |")
print("| -------- | ---- | ------- |")
for entry in sorted(results, key=lambda x: (x[2], x[1])):
    print(f"| {entry[2]:<42} | {entry[1]} | {entry[0]} |")

| Timeslot | Raum | AK-Name |
| -------- | ---- | ------- |
| So 10:30                                   | 107 | AK Vergütung für Fachschaftsarbeit |
| So 10:30/So 11:30                          | 209 | AK ReSopedia |
| So 10:30/So 9:30                           | 12 | AK Geschlechtergleichstellung |
| So 11:30                                   | 107 | AK Einstieg ins Mathestudium |
| So 11:30                                   | 11 | AK KIF-KoMa |
| So 14:00/So 15:00                          | 107 | AK Mental Health im Studium |
| So 14:00/So 15:00                          | 11 | AK Kurier |
| So 14:00/So 15:00/So 16:00/So 17:00/So 18:00 | 12 | AK Reso polieren |
| So 16:00                                   | 164 | AK Lehramt |
| So 16:00                                   | 209 | AK Orga |
| So 17:00/So 18:00                          | 107 | AK Meta |
| So 17:00/So 18:00                          | 209 | AK Problematische Dozierende |
| So 8:30                                    | 107 | AK Joint-Bachelor |
| So 8:30                                    | 12 | AK Stress bei Veranstaltungen |
| So 8:30                                    | 209 | AK Reso zu Ruheräumen |
| So 9:30                                    | 107 | AK Englischsprachige Studiengänge |
| So 9:30                                    | 164 | AK Multi-Faktor-Authentifizierung |

In [10]:
import pandas as pd
from IPython.display import HTML, display
display(HTML(pd.DataFrame(results).to_html(index=False)))

In [11]:
ak_plan = pd.pivot(pd.DataFrame(results), index=2, columns=1, values=0).fillna("")

In [12]:
ak_plan.to_csv("AK-Plan.csv")
display(HTML(ak_plan.to_html()))