In [5]:
from collections import defaultdict
import pandas as pd
import json

In [6]:
df = pd.read_csv("KoMa88_Kaiserslautern_AK-Präferenzen.csv")
df.head()

,Unnamed: 0,Vereinssitzung KoMa e.V.,AK Adresslistenaktualisierung,AK AK AK AK-Plan Programm,AK Arbeitszeiterfassung,AK Automatische Korrekturen,AK Awarenessarbeit,AK Berufungshandbuch,AK Datenschutz bei externer Software,AK Geschlechtergleichstellung,...,AK Prüfungsversuche,AK Kurier,AK KI-Anwendungen im Studium,AK Evaluation,AKkreditierung,AK Plenumsleitung,AK Budget-Fahrten,AK Koma-Büro,AK Nachhaltigkeitsmodule,Unnamed: 49
Fabian (Flexi),NaN,Nein,Nein,Nein,Nein,Nein,Unter Vorbehalt,Unter Vorbehalt,Nein,Unter Vorbehalt,...,Unter Vorbehalt,Nein,Unter Vorbehalt,Nein,Unter Vorbehalt,Nein,Nein,Nein,Unter Vorbehalt,NaN
Darline (Heidelberg),NaN,Nein,Nein,Nein,Nein,Nein,Nein,Ja,Nein,Nein,...,Unter Vorbehalt,Nein,Nein,Nein,Nein,Nein,Nein,Nein,Nein,NaN
Simon (Wien),NaN,Nein,Nein,Nein,Nein,Nein,Ja,Nein,Nein,Nein,...,Nein,Nein,Ja,Nein,Nein,Nein,Nein,Nein,Nein,NaN
Maxy (Hannover),NaN,Nein,Nein,Nein,Nein,Nein,Nein,Nein,Nein,Nein,...,Nein,Nein,Nein,Nein,Nein,Nein,Nein,Nein,Nein,NaN
Helen (Jena),NaN,Nein,Nein,Nein,Nein,Unter Vorbehalt,Unter Vorbehalt,Unter Vorbehalt,Nein,Nein,...,Unter Vorbehalt,Nein,Nein,Nein,Ja,Unter Vorbehalt,Ja,Nein,Nein,NaN

In [7]:
names = list(df.index)
assert len(names) == len(set(names))
sorted(names)

['Adrian',
 'Alex B',
 'Alicia (TU Chemnitz)',
 'Andreas Koch-Rein (Magdeburg) (Magdeburg)',
 'Annika (Graz)',
 'Antonia_JLU',
 'Asli (Bonn)',
 'BeneWue',
 'Bruno Btu',
 'Büsra (FAU Erlangen)',
 'Carina (Kiel)',
 'Caro (Bielefeld)',
 'Caroline (Erlangen)',
 'Darline (Heidelberg)',
 'Deike (Würzburg)',
 'Dennis (Darmstadt)',
 'Ellen',
 'Fabian (Flexi)',
 'Felix (Bonn)',
 'Fenna (Bielefeld)',
 'Gonne (Darmstadt)',
 'Grit',
 'Gustav',
 'Hannes (Essen)',
 'Helen (Jena)',
 'Immo (Bochum',
 'Janna',
 'Jil',
 'Johannes Jung',
 'Jonas Anthony Müller',
 'Jonas OvGU',
 'Jonas(Essen)',
 'Joscha (TU Darmstadt)',
 'Jurek',
 'Katharina (Göttingen)',
 'Kathi (Bielefeld)',
 'Lasse',
 'Lili (Bonn)',
 'Lorenzo (Bonn)',
 'Louis (Bonn)',
 'Lukas (Berlin)',
 'Lyon',
 'Marena (Bonn)',
 'Mark (HU Berlin)',
 'Matthias Hanl',
 'Matze (Freiburg)',
 'Max (TU Chemnitz)',
 'Maxy (Hannover)',
 'Mirj (Passau)',
 'Moritz',
 'Moses',
 'Nico',
 'Nika (Darmstadt)',
 'Niklas (JLU Gießen)',
 'Pia (Bochum)',
 'Robin',
 'Roman (Paderborn)',
 'Seb',
 'Simon (Bonn)',
 'Simon (Wien)',
 'Thalea',
 'Thomas (Bonn)',
 'Tim (Bremen)',
 'Tim (alterSack, Bonn - nicht da höchstens Samstag)',
 'Tobias Schmid (Bonn)',
 'Uschi (Jena)',
 'Wolf (RUB)',
 'Yoni (Jena)',
 'mmarx',
 'paul']

In [8]:
# ak_heads.difference(set(names))

NameError: name 'ak_heads' is not defined

In [ ]:
with open("KoMa-v2.json", "r") as f:
    lp_in = json.load(f)

In [ ]:
ak_names = [col_name for col_name in df.columns if "Unnamed" not in col_name]
assert len(ak_names) == len(set(ak_names)), "duplicate ak names"
print(ak_names)
df

['Vereinssitzung KoMa e.V.', 'AK Adresslistenaktualisierung', 'AK AK AK AK-Plan Programm', 'AK Arbeitszeiterfassung', 'AK Automatische Korrekturen', 'AK Awarenessarbeit', 'AK Berufungshandbuch', 'AK Datenschutz bei externer Software', 'AK Geschlechtergleichstellung', 'AK Hygiene bei Veranstaltungen', 'AK IT-Infrastruktur', 'AK Kartenspielwerbung', 'AK Klausurtermine', 'AK Lehramt', 'AK Lehrkraftmangel', 'AK Mentoring', 'AK Nachteilsausgleiche', 'AK Online-Wahl', 'AK Social Media', 'AK Spiel und Spaß', 'AK studentische Armut', 'AK TVStud', 'AK Veranstaltungen', 'AK WissZeitVG', 'AK Übungsleitungen', 'AK Studienwerbung', 'AK Zulassung zu Studiengängen', 'AK Spendenveranstaltungen', 'AK Angabe von Symptomen bei krankheitsbedingten Prüfungsabmeldungen', 'AK Gendergerechte Toiletten', 'AK Datenschutz bei Fachschaftsarbeit', 'AK Vereine von Fachschaften und Nachwuchs in Vereinen', 'AK Mental Health', 'AK bundesweites Semesterticket', 'AK Meta', 'AK Orga', 'AK KoMa-Homepage-Inhalt', 'AK Ethikmodule', 'AK Umgang mit Fachschaftsbeef', 'AK Prüfungsversuche', 'AK Kurier', 'AK KI-Anwendungen im Studium', 'AK Evaluation', 'AKkreditierung', 'AK Plenumsleitung', 'AK Budget-Fahrten', 'AK Koma-Büro', 'AK Nachhaltigkeitsmodule']

,Unnamed: 0,Vereinssitzung KoMa e.V.,AK Adresslistenaktualisierung,AK AK AK AK-Plan Programm,AK Arbeitszeiterfassung,AK Automatische Korrekturen,AK Awarenessarbeit,AK Berufungshandbuch,AK Datenschutz bei externer Software,AK Geschlechtergleichstellung,...,AK Prüfungsversuche,AK Kurier,AK KI-Anwendungen im Studium,AK Evaluation,AKkreditierung,AK Plenumsleitung,AK Budget-Fahrten,AK Koma-Büro,AK Nachhaltigkeitsmodule,Unnamed: 49
Fabian (Flexi),NaN,Nein,Nein,Nein,Nein,Nein,Unter Vorbehalt,Unter Vorbehalt,Nein,Unter Vorbehalt,...,Unter Vorbehalt,Nein,Unter Vorbehalt,Nein,Unter Vorbehalt,Nein,Nein,Nein,Unter Vorbehalt,NaN
Darline (Heidelberg),NaN,Nein,Nein,Nein,Nein,Nein,Nein,Ja,Nein,Nein,...,Unter Vorbehalt,Nein,Nein,Nein,Nein,Nein,Nein,Nein,Nein,NaN
Simon (Wien),NaN,Nein,Nein,Nein,Nein,Nein,Ja,Nein,Nein,Nein,...,Nein,Nein,Ja,Nein,Nein,Nein,Nein,Nein,Nein,NaN
Maxy (Hannover),NaN,Nein,Nein,Nein,Nein,Nein,Nein,Nein,Nein,Nein,...,Nein,Nein,Nein,Nein,Nein,Nein,Nein,Nein,Nein,NaN
Helen (Jena),NaN,Nein,Nein,Nein,Nein,Unter Vorbehalt,Unter Vorbehalt,Unter Vorbehalt,Nein,Nein,...,Unter Vorbehalt,Nein,Nein,Nein,Ja,Unter Vorbehalt,Ja,Nein,Nein,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Büsra (FAU Erlangen),NaN,Nein,Nein,Nein,Nein,Nein,Unter Vorbehalt,Nein,Ja,Unter Vorbehalt,...,Unter Vorbehalt,Unter Vorbehalt,Nein,Nein,Nein,Nein,Nein,Nein,Unter Vorbehalt,NaN
Max (TU Chemnitz),NaN,Nein,Nein,Nein,Unter Vorbehalt,Unter Vorbehalt,Unter Vorbehalt,Nein,Nein,Nein,...,Nein,Nein,Nein,Nein,Nein,Nein,Unter Vorbehalt,Nein,Nein,NaN
Alicia (TU Chemnitz),NaN,Nein,Nein,Nein,Unter Vorbehalt,Unter Vorbehalt,Unter Vorbehalt,Nein,Nein,Unter Vorbehalt,...,Nein,Nein,Nein,Nein,Nein,Nein,Unter Vorbehalt,Nein,Nein,NaN
Caroline (Erlangen),NaN,Nein,Nein,Nein,Nein,Nein,Unter Vorbehalt,Ja,Nein,Nein,...,Unter Vorbehalt,Nein,Unter Vorbehalt,Nein,Nein,Nein,Nein,Nein,Ja,NaN
"Tim (alterSack, Bonn - nicht da höchstens Samstag)",NaN,Nein,Nein,Ja,Nein,Nein,Nein,Nein,Nein,Nein,...,Nein,Nein,Nein,Nein,Nein,Nein,Nein,Nein,Nein,NaN

In [ ]:
ak_name_to_id_dict = {ak['info']['name']: ak['id'] for ak in lp_in['aks']}
part_name_to_id_dict = {part['info']['name']: part['id'] for part in lp_in['participants']}
print(ak_name_to_id_dict)

{'Vereinssitzung KoMa e.V.': 'verein'}

In [ ]:
def calc_pref_score(entry: str) -> int:
    if entry in ["Nein", "No"]:
        return 0
    elif entry in ["Ja", "Yes"]:
        return 2
    elif entry in ["Unter Vorbehalt", "Under reserve"]:
        return 1
    else:
        raise NotImplementedError
        
def get_part_dict(entries):
    name = entries.name
    if name in part_name_to_id_dict:
        return lp_in['participants'][part_name_to_id_dict[name]]
    i = 0
    while f"participant{i}" in part_name_to_id_dict.values():
        i+=1
    part_id = f"participant{i}"
    part_name_to_id_dict[name] = part_id
    participant_dict = {
        "id": part_id,
        "info": {"name": name},
        "time_constraints": [],
        "room_constraints": [],
        "preferences": [],
    }
    return participant_dict

In [ ]:
result_dict = lp_in

index_lst = []
for idx, entries in df.iterrows():
    
    participant_dict = get_part_dict(entries)

    for ak_name in ak_names:
        score = calc_pref_score(entries[ak_name])
        if score != 0:
            if ak_name in ak_name_to_id_dict:
                ak_id = ak_name_to_id_dict[ak_name]
            else:
                i = 0
                while f"ak{i}" in ak_name_to_id_dict.values():
                    i+=1
                ak_id = f"ak{i}"
                ak_name_to_id_dict[ak_name] = ak_id

            participant_dict["preferences"].append(
                {
                    "ak_id": ak_id,
                    "required": False,
                    "preference_score": score,
                }
            )
    if not participant_dict["preferences"]:
        continue
    result_dict["participants"].append(participant_dict)
    index_lst.append(idx)

assert len(index_lst) == len(set(index_lst)), "duplicate participant names"

In [ ]:
ak_df = pd.read_excel("AK_Liste_KoMa88.ods")
ak_df.head()

,AK-Name,Reso,Dauer,Leitung,Kurzbeschreibung,Bemerkungen zum AK (z.B. besondere Anforderungen)
0,AK Studienwerbung,0,2,Uschi (Jena),"Was wird an euren Hochschulen gemacht, um Math...",NaN
1,AK Adresslistenaktualisierung,0,1,Lili (Bonn),"Wir hatten vor, auch Fachschaften zur KoMa ein...",NaN
2,AK AK AK AK-Plan Programm,0,1,Lorenzo (Bonn),Seit der letzten KoMa gab es zwei WAch-KoMata ...,NaN
3,AK Arbeitszeiterfassung,1,2,Felix (Bonn),Bei allen Beschäftigten muss verpflichtend die...,NaN
4,AK Automatische Korrekturen,1,2,Pia (Bochum),"Wir würden uns gerne darüber austauschen, wie ...",NaN

In [ ]:
lst = []
for entry in ak_df["Leitung"]:
    for a in entry.split(","):
        lst.append(a.strip())

ak_heads = set(lst)
sorted(ak_heads)

['Annika (Graz)',
 'Asli (Bonn)',
 'Büsra (FAU Erlangen)',
 'Caro (Bielefeld)',
 'Darline (Heidelberg)',
 'Deike (Würzburg)',
 'Dennis (Darmstadt)',
 'Felix (Bonn)',
 'Hannes (Essen)',
 'Helen (Jena)',
 'Janna',
 'Lili (Bonn)',
 'Lorenzo (Bonn)',
 'Louis (Bonn)',
 'Lukas (Berlin)',
 'Marena (Bonn)',
 'Matze (Freiburg)',
 'Moritz',
 'Nika (Darmstadt)',
 'Pia (Bochum)',
 'Roman (Paderborn)',
 'Simon (Bonn)',
 'Simon (Wien)',
 'Uschi (Jena)',
 'Yoni (Jena)',
 'mmarx']

In [ ]:
for idx, row in ak_df.iterrows():
    print(row["Reso"])
    result_dict["aks"].append({
        "id": ak_name_to_id_dict[row["AK-Name"]],
        "duration": int(row["Dauer"]),
        "properties": {},
        "room_constraints": [],
        "time_constraints": ["reso_time"] if row["Reso"] else [],
        "info": {
            "name": row["AK-Name"],
            "head": row["Leitung"],
            "description": row["Kurzbeschreibung"],
            "reso": bool(row["Reso"])
        }
    })

0
0
0
1
1
0
0
0
0
0
0
0
1
0
1
0
0
1
1
0
0
1
1
1
0
0
0
0
0
0
1
0
0
1
1
0
0
0
0
0
0
0
0
0
0
0
0

In [ ]:
result_dict

{'rooms': [{'id': '48_208',
   'info': {'name': 'Gebäude 48 Raum 208'},
   'capacity': 98,
   'fulfilled_room_constraints': ['beamer'],
   'time_constraints': []},
  {'id': '48_210',
   'info': {'name': 'Gebäude 48 Raum 210'},
   'capacity': 98,
   'fulfilled_room_constraints': ['verein_room', 'beamer'],
   'time_constraints': []},
  {'id': '48_438',
   'info': {'name': 'Gebäude 48 Raum 438'},
   'capacity': 25,
   'fulfilled_room_constraints': ['ak_room', 'beamer', 'keine_treppen'],
   'time_constraints': []},
  {'id': '48_538',
   'info': {'name': 'Gebäude 48 Raum 538'},
   'capacity': 30,
   'fulfilled_room_constraints': ['beamer', 'keine_treppen'],
   'time_constraints': []},
  {'id': '48-582',
   'info': {'name': 'Gebäude 48 Raum 582'},
   'capacity': 35,
   'fulfilled_room_constraints': ['ak_room', 'beamer', 'keine_treppen'],
   'time_constraints': ['not_fr1415']},
  {'id': '46-267',
   'capacity': 45,
   'info': {'name': 'Gebäude 46 Raum 267'},
   'time_constraints': ['not_friday'],
   'fulfilled_room_constraints': ['ak_room', 'keine_treppen']},
  {'id': '11_201',
   'info': {'name': 'Gebäude 11 Raum 201'},
   'capacity': 20,
   'fulfilled_room_constraints': ['beamer', 'ak_room', 'keine_treppen'],
   'time_constraints': ['not_thursday', 'not_saturday']},
  {'id': '11_243',
   'info': {'name': 'Gebäude 11 Raum 243'},
   'capacity': 60,
   'fulfilled_room_constraints': ['beamer', 'ak_room', 'keine_treppen'],
   'time_constraints': ['not_thursday', 'not_saturday']},
  {'id': '11-220',
   'info': {'name': 'Gebäude 11 Raum 220'},
   'capacity': 20,
   'time_constraints': ['not_thursday', 'not_saturday'],
   'fulfilled_room_constraints': ['ak_room', 'keine_treppen']}],
 'timeslots': {'info': {'duration': '1 hour blocks'},
  'blocks': [[{'id': 'DoM0',
     'info': {'start': 'Donnerstag 8:00'},
     'fulfilled_time_constraints': ['not_friday',
      'not_saturday',
      'reso_time',
      'not_fr1415']},
    {'id': 'DoM1',
     'info': {'start': 'Donnerstag 9:00'},
     'fulfilled_time_constraints': ['not_friday',
      'not_saturday',
      'reso_time',
      'not_fr1415']},
    {'id': 'DoM2',
     'info': {'start': 'Donnerstag 10:00'},
     'fulfilled_time_constraints': ['not_friday',
      'not_saturday',
      'reso_time',
      'not_fr1415']},
    {'id': 'DoM3',
     'info': {'start': 'Donnerstag 11:00'},
     'fulfilled_time_constraints': ['not_friday',
      'not_saturday',
      'reso_time',
      'not_fr1415']}],
   [{'id': 'DoA0',
     'info': {'start': 'Donnerstag 14:00'},
     'fulfilled_time_constraints': ['not_friday',
      'not_saturday',
      'reso_time',
      'not_fr1415']},
    {'id': 'DoA1',
     'info': {'start': 'Donnerstag 15:00'},
     'fulfilled_time_constraints': ['not_friday',
      'not_saturday',
      'reso_time',
      'not_fr1415']},
    {'id': 'DoA2',
     'info': {'start': 'Donnerstag 16:00'},
     'fulfilled_time_constraints': ['not_friday',
      'not_saturday',
      'reso_time',
      'not_fr1415']},
    {'id': 'DoA3',
     'info': {'start': 'Donnerstag 17:00'},
     'fulfilled_time_constraints': ['not_friday',
      'not_saturday',
      'reso_time',
      'not_fr1415']}],
   [{'id': 'FrA0',
     'info': {'start': 'Freitag 14:00'},
     'fulfilled_time_constraints': ['not_thursday',
      'not_saturday',
      'reso_time']},
    {'id': 'FrA1',
     'info': {'start': 'Freitag 15:00'},
     'fulfilled_time_constraints': ['not_thursday',
      'not_saturday',
      'reso_time',
      'not_fr1415']},
    {'id': 'FrA2',
     'info': {'start': 'Freitag 16:00'},
     'fulfilled_time_constraints': ['not_thursday',
      'not_saturday',
      'not_fr1415']},
    {'id': 'FrA3',
     'info': {'start': 'Freitag 17:00'},
     'fulfilled_time_constraints': ['not_thursday',
      'not_saturday',
      'not_fr1415']},
    {'id': 'FrA4',
     'info': {'start': 'Freitag 18:00'},
     'fulfilled_time_constraints': ['not_thursday',
      'not_saturday',
      'not_fr1415']}],
   [{'id': 'SaM0',
     'info': {'start': 'Samstag 8:00'},
     'fulfilled_time_constraints': ['not_thursday',
      'not_friday',
      'not_fr1415']},
    {'id': 'SaM1',
     'info': {'start': 'Samstag 9:00'},
     'fulfilled_time_constraints': ['not_thursday',
      'not_friday',
      'not_fr1415']},
    {'id': 'SaM2',
     'info': {'start': 'Samstag 10:00'},
     'fulfilled_time_constraints': ['not_thursday',
      'not_friday',
      'not_fr1415']},
    {'id': 'SaM3',
     'info': {'start': 'Samstag 11:00'},
     'fulfilled_time_constraints': ['not_thursday',
      'not_friday',
      'not_fr1415']}],
   [{'id': 'SaA0',
     'info': {'start': 'Samstag 14:00'},
     'fulfilled_time_constraints': ['not_thursday',
      'not_friday',
      'not_fr1415',
      'verein_time']},
    {'id': 'SaA1',
     'info': {'start': 'Samstag 15:00'},
     'fulfilled_time_constraints': ['not_thursday',
      'not_friday',
      'not_fr1415',
      'verein_time']},
    {'id': 'SaA2',
     'info': {'start': 'Samstag 16:00'},
     'fulfilled_time_constraints': ['not_thursday',
      'not_friday',
      'not_fr1415']},
    {'id': 'SaA3',
     'info': {'start': 'Samstag 17:00'},
     'fulfilled_time_constraints': ['not_thursday',
      'not_friday',
      'not_fr1415']},
    {'id': 'SaA4',
     'info': {'start': 'Samstag 18:00'},
     'fulfilled_time_constraints': ['not_thursday',
      'not_friday',
      'not_fr1415']}]]},
 'aks': [{'id': 'verein',
   'duration': 2,
   'properties': {},
   'room_constraints': ['verein_room'],
   'time_constraints': ['verein_time'],
   'info': {'name': 'Vereinssitzung KoMa e.V.',
    'head': 'Ushi?',
    'description': '',
    'reso': False}},
  {'id': 'ak5',
   'duration': 2,
   'properties': {},
   'room_constraints': [],
   'time_constraints': [],
   'info': {'name': 'AK Studienwerbung',
    'head': 'Uschi (Jena)',
    'description': 'Was wird an euren Hochschulen gemacht, um Mathe-(Lehramts-)Studis zu gewinnen? Welche Veranstaltungen gibt es bei euch? Wobei seid ihr involviert? Was funktioniert eurer Meinung nach, was nicht? ',
    'reso': False}},
  {'id': 'ak34',
   'duration': 1,
   'properties': {},
   'room_constraints': [],
   'time_constraints': [],
   'info': {'name': 'AK Adresslistenaktualisierung',
    'head': 'Lili (Bonn)',
    'description': 'Wir hatten vor, auch Fachschaften zur KoMa einzuladen, die Mathe-verwandte Fächer wie Data Science vertreten, aber keine klassische Mathe-Fachschaft sind. Die Aktualisierung der Adresslisten dazu könnte man fortführen. ',
    'reso': False}},
  {'id': 'ak40',
   'duration': 1,
   'properties': {},
   'room_constraints': [],
   'time_constraints': [],
   'info': {'name': 'AK AK AK AK-Plan Programm',
    'head': 'Lorenzo (Bonn) ',
    'description': 'Seit der letzten KoMa gab es zwei WAch-KoMata zu einem Programm zur Optimierung von AK-Plänen. Aktueller Stand hier: https://github.com/die-koma/ak-plan-optimierung/tree/lorenzo_lp_formulationWenn alles geklappt hat, lief die Optimierung des AK-Plans bereits über das Programm. Wir wollen darüber und die nächsten Schritte des Projekts sprechen (und diese ggf. auf der KoMa bereits angehen). ',
    'reso': False}},
  {'id': 'ak41',
   'duration': 2,
   'properties': {},
   'room_constraints': [],
   'time_constraints': ['reso_time'],
   'info': {'name': 'AK Arbeitszeiterfassung',
    'head': 'Felix (Bonn)',
    'description': 'Bei allen Beschäftigten muss verpflichtend die Arbeitszeit erfasst werden. Das ist in der Uni nicht flächendeckend und ggf. unzureichend umgesetzt.Gleichzeitig führt die Erfassung der Arbeitszeiten oft zu Konflikten mit bestehenden Praxen und clasht mit Problemen im Wissenschaftssystem, wie z.B. Promotionsstudis auf Nicht-Vollzeitstellen. ',
    'reso': True}},
  {'id': 'ak19',
   'duration': 2,
   'properties': {},
   'room_constraints': [],
   'time_constraints': ['reso_time'],
   'info': {'name': 'AK Automatische Korrekturen',
    'head': 'Pia (Bochum)',
    'description': "Wir würden uns gerne darüber austauschen, wie automatische Korrekturen (z.B. der Übungsaufgaben ganzer Veranstaltungen) vernünftig umgesetzt werden können (und wie nicht), inwiefern das Stellen 'spart', bzw. Arbeit kurz- und langfristig reduziert, und welchen Einfluss das auf Studierende hat. ",
    'reso': True}},
  {'id': 'ak0',
   'duration': 2,
   'properties': {},
   'room_constraints': [],
   'time_constraints': [],
   'info': {'name': 'AK Awarenessarbeit',
    'head': 'Simon (Wien)',
    'description': 'Awarenessworkshops bzw. Bildung sehr teuer, daher Austausch sinnvoll. ',
    'reso': False}},
  {'id': 'ak1',
   'duration': 2,
   'properties': {},
   'room_constraints': [],
   'time_constraints': [],
   'info': {'name': 'AK Berufungshandbuch',
    'head': 'mmarx',
    'description': 'Die KIF hat Interesse an einer Ueberarbeitung des Berufungshandbuchs. Da das auch fuer uns interessant ist, ist die Idee, hier einen Hybrid-AK zum Austausch ueber Berufungsverfahren und ggf. zur Ueberarbeitung des Texts anzubieten',
    'reso': False}},
  {'id': 'ak42',
   'duration': 1,
   'properties': {},
   'room_constraints': [],
   'time_constraints': [],
   'info': {'name': 'AK Datenschutz bei externer Software',
    'head': 'Büsra (FAU Erlangen) ',
    'description': 'Bei unserer Uni gibt es einige Probleme mit Software von dritten Anbietern, die unsere Uni nutzt. Durch automatisierte Systeme, die für die Verwaltung sicher nützlich sind, werden Kontaktdaten etc. von Studis ohne deren Wissen für alle 40-50k Leute der Uni sichtbar.',
    'reso': False}},
  {'id': 'ak2',
   'duration': 2,
   'properties': {},
   'room_constraints': [],
   'time_constraints': [],
   'info': {'name': 'AK Geschlechtergleichstellung',
    'head': 'Marena (Bonn)',
    'description': ' Austausch darüber, welche Maßnahmen an den verschiedenen Unis stattfinden, um an der Geschlechtergleichstellung zu arbeiten. Was macht der Fachbereich, was macht die Fachschaft? ',
    'reso': False}},
  {'id': 'ak38',
   'duration': 1,
   'properties': {},
   'room_constraints': [],
   'time_constraints': [],
   'info': {'name': 'AK Hygiene bei Veranstaltungen',
    'head': 'Büsra (FAU Erlangen) ',
    'description': 'Wie gehen andere Fachschaften mit Hygienekonzepten bei Festen/Veranstaltungen um? Wie werden Regelungen enforced? Wie streng wird sich an sowas wie die Kühlkette beim Einkauf/Transport gehalten? ',
    'reso': False}},
  {'id': 'ak43',
   'duration': 1,
   'properties': {},
   'room_constraints': [],
   'time_constraints': [],
   'info': {'name': 'AK IT-Infrastruktur',
    'head': 'mmarx',
    'description': 'Austausch ueber und gegebenfalls produktive Arbeit an IT-Infrastruktur (primaer der KoMa selbst, aber wir koennen auch gerne ueber FSR-Infrastruktur reden). ',
    'reso': False}},
  {'id': 'ak35',
   'duration': 1,
   'properties': {},
   'room_constraints': [],
   'time_constraints': [],
   'info': {'name': 'AK Kartenspielwerbung',
    'head': 'Yoni (Jena), Lili (Bonn)',
    'description': 'Der KoMa e.V. hat endlich neue Kartenspiele. Allerdings sind die Bestellung über die Jahre immer weniger geworden und spätestens Corona bzw. die lange Zeit ohne Kartenspiele hat das nur noch schlimmer gemacht. Daher sollten wir uns überlegen, wie wir die neuen Kartenspiele gut bewerben könnten. ',
    'reso': False}},
  {'id': 'ak12',
   'duration': 2,
   'properties': {},
   'room_constraints': [],
   'time_constraints': ['reso_time'],
   'info': {'name': 'AK Klausurtermine',
    'head': 'Büsra (FAU Erlangen) ',
    'description': 'Auf der KoMa 84 in Augsburg gab es eine Reso zum Thema rechtzeitige Ankündigung von Prüfungsterminen. Da die Zeit sehr fortgeschritten war und kein Ende in Sicht war in der Anpassung der Reso, wurde das Ganze auf eine zukünftige KoMa geschoben. Ist wohl ein wenig aus den Augen gelaufen, daher jetzt ein wenig später als geplant der neue AK dazu. ',
    'reso': True}},
  {'id': 'ak20',
   'duration': 2,
   'properties': {},
   'room_constraints': [],
   'time_constraints': [],
   'info': {'name': 'AK Lehramt',
    'head': 'Asli (Bonn)',
    'description': 'Austausch über die Struktur der Lehramtsstudiengänge an verschiedenen Hochschulen, Aufzeigen von Problemen, Austausch über Lösungskonzepte ',
    'reso': False}},
  {'id': 'ak13',
   'duration': 2,
   'properties': {},
   'room_constraints': [],
   'time_constraints': ['reso_time'],
   'info': {'name': 'AK Lehrkraftmangel',
    'head': 'Yoni (Jena)',
    'description': 'Reso der ZaPF (Physik BuFaTa), der wir uns anschließen können (ggf. haben auch ein zwei Lehramtsmenschen noch was aus Mathe-Sicht zu ergänzen) ',
    'reso': True}},
  {'id': 'ak21',
   'duration': 1,
   'properties': {},
   'room_constraints': [],
   'time_constraints': [],
   'info': {'name': 'AK Mentoring',
    'head': 'Nika (Darmstadt)',
    'description': 'Wir hätten gerne Input dazu, wie Mentoring bei euch an der Uni funktioniert. ',
    'reso': False}},
  {'id': 'ak11',
   'duration': 1,
   'properties': {},
   'room_constraints': [],
   'time_constraints': [],
   'info': {'name': 'AK Nachhaltigkeitsmodule',
    'head': 'Deike (Würzburg)',
    'description': 'Die Uni Würzburg will vllt/evtl bis xx in jedem Studiengang ein Nachhaltigkeitsmodul haben, in der Mathe fehlt die Kreativität dazu ',
    'reso': False}},
  {'id': 'ak22',
   'duration': 2,
   'properties': {},
   'room_constraints': [],
   'time_constraints': ['reso_time'],
   'info': {'name': 'AK Nachteilsausgleiche',
    'head': 'Asli (Bonn)',
    'description': 'Auf der letzten KoMa wurde im AK Inklusion das Thema Nachteilsausgleich im Rahmen ADHS angesprochen und wir haben gesagt, dass wir das Thema auf die nächste KoMa verschieben wollen, weil das einen eigenen AK verdient hat. Es soll diskutiert werden, welche Arten von Nachteilsausgleichen notwendig wären und wie man diese erreichen kann. Das soll dann evtl in einer Reso formuliert werden. ',
    'reso': True}},
  {'id': 'ak17',
   'duration': 2,
   'properties': {},
   'room_constraints': [],
   'time_constraints': ['reso_time'],
   'info': {'name': 'AK Online-Wahl',
    'head': 'Dennis (Darmstadt)',
    'description': 'Wir finden Onlinewahlen blöd. ',
    'reso': True}},
  {'id': 'ak23',
   'duration': 1,
   'properties': {},
   'room_constraints': [],
   'time_constraints': [],
   'info': {'name': 'AK Social Media',
    'head': 'Roman (Paderborn)',
    'description': 'Ungenutzte Facebook-Seite & Telegram; potentiell weitere Plattformen?',
    'reso': False}},
  {'id': 'ak18',
   'duration': 2,
   'properties': {},
   'room_constraints': [],
   'time_constraints': [],
   'info': {'name': 'AK Spiel und Spaß',
    'head': 'Janna, Annika (Graz)',
    'description': 'Austausch und Durchführung von kurzen Spielen und Warm Ups, die auch in Veranstaltung als kurze Lockerung eingesetzt werden können ',
    'reso': False}},
  {'id': 'ak3',
   'duration': 2,
   'properties': {},
   'room_constraints': [],
   'time_constraints': ['reso_time'],
   'info': {'name': 'AK studentische Armut',
    'head': 'Moritz',
    'description': 'Studentische Armut ist mit Krieg, Inflation und schlechte Arbeitsbedingungen einer immer größeres Thema. Dazu sollte sich auch die KoMa positionieren. ',
    'reso': True}},
  {'id': 'ak4',
   'duration': 2,
   'properties': {},
   'room_constraints': [],
   'time_constraints': ['reso_time'],
   'info': {'name': 'AK TVStud',
    'head': 'Felix (Bonn)',
    'description': 'Es soll über einen Tarifvertrag für studentische Beschäftigte gesprochen werden. ',
    'reso': True}},
  {'id': 'ak25',
   'duration': 2,
   'properties': {},
   'room_constraints': [],
   'time_constraints': ['reso_time'],
   'info': {'name': 'AK WissZeitVG',
    'head': 'Felix (Bonn)',
    'description': 'Austausch und ggf. Positionierung zur Novellierung des Wissenschaftszeitvertragsgesetzes, welches die Sonderbefristungsrechte in der Wissenschaft regelt. ',
    'reso': True}},
  {'id': 'ak26',
   'duration': 2,
   'properties': {},
   'room_constraints': [],
   'time_constraints': [],
   'info': {'name': 'AK Übungsleitungen',
    'head': 'Louis (Bonn)',
    'description': 'Wir möchten uns über die Arbeitsbedingungen der studentischen Beschäftigen an anderen Hochschule in Deutschland erkundigen. Sowie über die Probleme vieler Hochschulen sprechen, dass immer mehr ÜL Stellen gestrichen werden (was kann man da tun? ).',
    'reso': False}},
  {'id': 'ak37',
   'duration': 1,
   'properties': {},
   'room_constraints': [],
   'time_constraints': [],
   'info': {'name': 'AK Koma-Büro',
    'head': 'Lili (Bonn)',
    'description': 'Da das KoMa-Büro wurde letzte KoMa von Bonn übernommen. Wir würden uns gern über die Aufgaben und Erwartungen an das KoMa-Büro austauschen. ',
    'reso': False}},
  {'id': 'ak24',
   'duration': 2,
   'properties': {},
   'room_constraints': [],
   'time_constraints': [],
   'info': {'name': 'AK Veranstaltungen',
    'head': 'Nika (Darmstadt)',
    'description': 'Wie funktionieren größere Veranstaltungen bei euch bzgl Sicherheitsdienst, Veranstaltungsleitung,...? Vor allem gerichtet an Hochschule in Hessen im Zuge des neuen Versammlungsgesetzes. ',
    'reso': False}},
  {'id': 'ak27',
   'duration': 1,
   'properties': {},
   'room_constraints': [],
   'time_constraints': [],
   'info': {'name': 'AK Zulassung zu Studiengängen',
    'head': 'Helen (Jena)',
    'description': 'Es ist irgendwie nicht ganz so trivial, wie mal möglichst sinnvoll festmachen kann ob Menschen qualifiziert sind z.B. einen Mathe Master zu studieren, wie läuft das bei euch? Was kann man da tun? ',
    'reso': False}},
  {'id': 'ak28',
   'duration': 1,
   'properties': {},
   'room_constraints': [],
   'time_constraints': [],
   'info': {'name': 'AK Spendenveranstaltungen',
    'head': 'Helen (Jena)',
    'description': 'Für größere Veranstaltungen haben wir zuletzt versucht Spenden von Professoren einzuwerben, das ist bei uns nicht sonderlich erfolgreich. Was macht ihr da? ',
    'reso': False}},
  {'id': 'ak39',
   'duration': 1,
   'properties': {},
   'room_constraints': [],
   'time_constraints': [],
   'info': {'name': 'AK Gendergerechte Toiletten',
    'head': 'Hannes (Essen)',
    'description': nan,
    'reso': False}},
  {'id': 'ak29',
   'duration': 1,
   'properties': {},
   'room_constraints': [],
   'time_constraints': ['reso_time'],
   'info': {'name': 'AK Angabe von Symptomen bei krankheitsbedingten Prüfungsabmeldungen',
    'head': 'Yoni (Jena)',
    'description': 'Metafa-Reso dazu',
    'reso': True}},
  {'id': 'ak44',
   'duration': 1,
   'properties': {},
   'room_constraints': [],
   'time_constraints': [],
   'info': {'name': 'AK Datenschutz bei Fachschaftsarbeit',
    'head': 'Hannes (Essen)',
    'description': 'An unserer Uni weiß niemand so recht Bescheid, wie man DSGVO-konform Fachscjaftsarbeit umsetzt, insbesondere beim Thema Fotos',
    'reso': False}},
  {'id': 'ak30',
   'duration': 1,
   'properties': {},
   'room_constraints': [],
   'time_constraints': [],
   'info': {'name': 'AK Vereine von Fachschaften und Nachwuchs in Vereinen',
    'head': 'Helen (Jena)',
    'description': 'Vereine und Vereinsarbeit ist wichtig, da sollte man mal drüber sprechen und wie man da auch neue Leute reinbekommt',
    'reso': False}},
  {'id': 'ak6',
   'duration': 2,
   'properties': {},
   'room_constraints': [],
   'time_constraints': ['reso_time'],
   'info': {'name': 'AK Mental Health',
    'head': 'Simon (Bonn)',
    'description': 'Austausch über die aktuelle Situation bzgl. Mental Health in der Studierendenschaft. Evtl. Reso zur Sichtbarkeit und Umgang damit',
    'reso': True}},
  {'id': 'ak7',
   'duration': 1,
   'properties': {},
   'room_constraints': [],
   'time_constraints': ['reso_time'],
   'info': {'name': 'AK bundesweites Semesterticket',
    'head': 'Matze (Freiburg)',

In [ ]:
with open("export.json", "w") as f:
    json.dump(result_dict, f, indent=4)