In [42]:
import json
import numpy as np

In [43]:
with open("out-export.json", "r") as f:
    result = json.load(f)

scheduled_aks = result["scheduled_aks"]
inputs = result["input"]

results = []

for ak in scheduled_aks:
    ak_id = ak["ak_id"]
    room_id = ak["room_id"]
    timeslot_ids = ak["timeslot_ids"]

    timeslot_names = []
    for timeslot_id in timeslot_ids:
        for block in inputs["timeslots"]["blocks"]:
            for timeslot in block:
                if timeslot["id"] == timeslot_id:
                    timeslot_names.append(timeslot["info"]["start"])
                    break
            else:
                continue
            break

    timeslot_names = "/".join(sorted(timeslot_names))
    
    for room in inputs["rooms"]:
        if room["id"] == room_id:
            room_name = room["info"]["name"]
            break
    
    # print(ak_id, sorted([t["id"] for t in inputs["aks"]]))
    for ak in inputs["aks"]:
        if ak["id"] == ak_id:
            ak_name = ak["info"]["name"]
            break

    results.append((ak_name, room_name, timeslot_names))

In [44]:
print("| Timeslot | Raum | AK-Name |")
print("| -------- | ---- | ------- |")
for entry in sorted(results, key=lambda x: (x[2], x[1])):
    print(f"| {entry[2]:<42} | {entry[1]} | {entry[0]} |")

| Timeslot | Raum | AK-Name |
| -------- | ---- | ------- |
| Donnerstag 10:00                           | Gebäude 46 Raum 267 | AK bundesweites Semesterticket |
| Donnerstag 10:00/Donnerstag 11:00          | Gebäude 48 Raum 438 | AK Arbeitszeiterfassung |
| Donnerstag 10:00/Donnerstag 9:00           | Gebäude 48 Raum 538 | AK KoMa-Homepage-Inhalt |
| Donnerstag 11:00                           | Gebäude 48 Raum 208 | AK Angabe von Symptomen bei krankheitsbedingten Prüfungsabmeldungen |
| Donnerstag 11:00                           | Gebäude 48 Raum 538 | AK AK AK AK-Plan Programm |
| Donnerstag 11:00                           | Gebäude 48 Raum 582 | AK Kartenspielwerbung |
| Donnerstag 14:00/Donnerstag 15:00          | Gebäude 46 Raum 267 | AK Klausurtermine |
| Donnerstag 14:00/Donnerstag 15:00          | Gebäude 48 Raum 208 | AK Awarenessarbeit |
| Donnerstag 14:00/Donnerstag 15:00          | Gebäude 48 Raum 538 | AK WissZeitVG |
| Donnerstag 16:00/Donnerstag 17:00          | Gebäude 46 Raum 267 | AK studentische Armut |
| Donnerstag 16:00/Donnerstag 17:00          | Gebäude 48 Raum 208 | AK Spiel und Spaß |
| Donnerstag 16:00/Donnerstag 17:00          | Gebäude 48 Raum 210 | AK Nachteilsausgleiche |
| Donnerstag 16:00/Donnerstag 17:00          | Gebäude 48 Raum 582 | AK Automatische Korrekturen |
| Donnerstag 8:00                            | Gebäude 46 Raum 267 | AK KI-Anwendungen im Studium |
| Donnerstag 8:00                            | Gebäude 48 Raum 582 | AK Gendergerechte Toiletten |
| Donnerstag 8:00/Donnerstag 9:00            | Gebäude 48 Raum 208 | AK Lehrkraftmangel |
| Donnerstag 8:00/Donnerstag 9:00            | Gebäude 48 Raum 438 | AK TVStud |
| Donnerstag 9:00                            | Gebäude 48 Raum 210 | AK Nachhaltigkeitsmodule |
| Freitag 14:00/Freitag 15:00                | Gebäude 11 Raum 243 | AK Mental Health |
| Freitag 14:00/Freitag 15:00                | Gebäude 48 Raum 210 | AK Studienwerbung |
| Freitag 14:00/Freitag 15:00                | Gebäude 48 Raum 538 | AK Online-Wahl |
| Freitag 16:00                              | Gebäude 48 Raum 210 | AK Plenumsleitung |
| Freitag 16:00                              | Gebäude 48 Raum 538 | AK Ethikmodule |
| Freitag 16:00                              | Gebäude 48 Raum 582 | AK Adresslistenaktualisierung |
| Freitag 17:00                              | Gebäude 48 Raum 208 | AK Datenschutz bei externer Software |
| Freitag 17:00/Freitag 18:00                | Gebäude 48 Raum 210 | AK Lehramt |
| Freitag 18:00                              | Gebäude 48 Raum 208 | AK Hygiene bei Veranstaltungen |
| Freitag 18:00                              | Gebäude 48 Raum 438 | AK IT-Infrastruktur |
| Samstag 10:00                              | Gebäude 48 Raum 210 | AK Mentoring |
| Samstag 10:00                              | Gebäude 48 Raum 582 | AK Prüfungsversuche |
| Samstag 11:00                              | Gebäude 46 Raum 267 | AK Spendenveranstaltungen |
| Samstag 11:00                              | Gebäude 48 Raum 538 | AK Orga |
| Samstag 14:00/Samstag 15:00                | Gebäude 48 Raum 208 | AK Geschlechtergleichstellung |
| Samstag 14:00/Samstag 15:00                | Gebäude 48 Raum 210 | AK Meta |
| Samstag 14:00/Samstag 15:00                | Gebäude 48 Raum 582 | AK Übungsleitungen |
| Samstag 16:00                              | Gebäude 46 Raum 267 | AK Budget-Fahrten |
| Samstag 16:00                              | Gebäude 48 Raum 210 | AK Social Media |
| Samstag 16:00/Samstag 17:00                | Gebäude 48 Raum 438 | AK Berufungshandbuch |
| Samstag 17:00                              | Gebäude 48 Raum 582 | AK Veranstaltungen |
| Samstag 18:00                              | Gebäude 48 Raum 208 | AK Umgang mit Fachschaftsbeef |
| Samstag 18:00                              | Gebäude 48 Raum 582 | AK Evaluation |
| Samstag 8:00                               | Gebäude 46 Raum 267 | AKkreditierung |
| Samstag 8:00                               | Gebäude 48 Raum 438 | AK Kurier |
| Samstag 8:00                               | Gebäude 48 Raum 538 | AK Zulassung zu Studiengängen |
| Samstag 9:00                               | Gebäude 48 Raum 208 | AK Koma-Büro |
| Samstag 9:00                               | Gebäude 48 Raum 210 | AK Datenschutz bei Fachschaftsarbeit |
| Samstag 9:00                               | Gebäude 48 Raum 538 | AK Vereine von Fachschaften und Nachwuchs in Vereinen |

In [45]:
import pandas as pd
from IPython.display import HTML, display
display(HTML(pd.DataFrame(results).to_html(index=False)))

In [48]:
pd.pivot(pd.DataFrame(results), index=2, columns=1, values=0).fillna("").loc

1,Gebäude 11 Raum 243,Gebäude 46 Raum 267,Gebäude 48 Raum 208,Gebäude 48 Raum 210,Gebäude 48 Raum 438,Gebäude 48 Raum 538,Gebäude 48 Raum 582
2,,,,,,,
Donnerstag 10:00,,AK bundesweites Semesterticket,,,,,
Donnerstag 10:00/Donnerstag 11:00,,,,,AK Arbeitszeiterfassung,,
Donnerstag 10:00/Donnerstag 9:00,,,,,,AK KoMa-Homepage-Inhalt,
Donnerstag 11:00,,,AK Angabe von Symptomen bei krankheitsbedingte...,,,AK AK AK AK-Plan Programm,AK Kartenspielwerbung
Donnerstag 14:00/Donnerstag 15:00,,AK Klausurtermine,AK Awarenessarbeit,,,AK WissZeitVG,
Donnerstag 16:00/Donnerstag 17:00,,AK studentische Armut,AK Spiel und Spaß,AK Nachteilsausgleiche,,,AK Automatische Korrekturen
Donnerstag 8:00,,AK KI-Anwendungen im Studium,,,,,AK Gendergerechte Toiletten
Donnerstag 8:00/Donnerstag 9:00,,,AK Lehrkraftmangel,,AK TVStud,,
Donnerstag 9:00,,,,AK Nachhaltigkeitsmodule,,,
Freitag 14:00/Freitag 15:00,AK Mental Health,,,AK Studienwerbung,,AK Online-Wahl,
Freitag 16:00,,,,AK Plenumsleitung,,AK Ethikmodule,AK Adresslistenaktualisierung
Freitag 17:00,,,AK Datenschutz bei externer Software,,,,
Freitag 17:00/Freitag 18:00,,,,AK Lehramt,,,
Freitag 18:00,,,AK Hygiene bei Veranstaltungen,,AK IT-Infrastruktur,,
Samstag 10:00,,,,AK Mentoring,,,AK Prüfungsversuche
Samstag 11:00,,AK Spendenveranstaltungen,,,,AK Orga,
Samstag 14:00/Samstag 15:00,,,AK Geschlechtergleichstellung,AK Meta,,,AK Übungsleitungen
Samstag 16:00,,AK Budget-Fahrten,,AK Social Media,,,
Samstag 16:00/Samstag 17:00,,,,,AK Berufungshandbuch,,
Samstag 17:00,,,,,,,AK Veranstaltungen
Samstag 18:00,,,AK Umgang mit Fachschaftsbeef,,,,AK Evaluation
Samstag 8:00,,AKkreditierung,,,AK Kurier,AK Zulassung zu Studiengängen,
Samstag 9:00,,,AK Koma-Büro,AK Datenschutz bei Fachschaftsarbeit,,AK Vereine von Fachschaften und Nachwuchs in V...,