In [74]:
from collections import defaultdict
import pandas as pd
import json

In [75]:
ak_df = pd.read_excel("AK_Liste_KoMa88.ods")
ak_df.head()

,AK-Name,Reso,Dauer (in Stunden),Leitung,Kurzbeschreibung,Bemerkungen zum AK (z.B. besondere Anforderungen)
0,AK Studienwerbung,False,2,Uschi (Jena),"Was wird an euren Hochschulen gemacht, um Math...",NaN
1,AK Adresslistenaktualisierung,False,1,Lili (Bonn),"Wir hatten vor, auch Fachschaften zur KoMa ein...",NaN
2,AK AK AK AK-Plan Programm,False,1,Lorenzo (Bonn),Seit der letzten KoMa gab es zwei WAch-KoMata ...,NaN
3,AK Arbeitszeiterfassung,False,2,Felix (Bonn),Bei allen Beschäftigten muss verpflichtend die...,NaN
4,AK Automatische Korrekturen,False,2,Pia (Bochum),"Wir würden uns gerne darüber austauschen, wie ...",NaN

In [76]:
lst = []
for entry in ak_df["Leitung"]:
    for a in entry.split(","):
        lst.append(a.strip())

ak_heads = set(lst)
sorted(ak_heads)

['Annika',
 'Asli (Bonn)',
 'Büsra (FAU Erlangen)',
 'Caro (Bielefeld)',
 'Darline (Uni Heidelberg)',
 'Deike',
 'Dennis (Darmstadt)',
 'Felix (Bonn)',
 'Hannes (Essen)',
 'Helen (Jena)',
 'Janna',
 'Lili (Bonn)',
 'Lorenzo (Bonn)',
 'Louis (Bonn)',
 'Lukas (Berlin)',
 'Marena (Bonn)',
 'Matze (Freiburg)',
 'Moritz',
 'Nika (Darmstadt)',
 'Pia (Bochum)',
 'Roman (Paderborn)',
 'Simon (Bonn)',
 'Simon (Wien)',
 'Uschi (Jena)',
 'Yoni (Jena)',
 'mmarx']

In [77]:
df = pd.read_csv("KoMa88_Kaiserslautern_AK-Präferenzen.csv")
df.head()

,Unnamed: 0,Vereinssitzung KoMa e.V.,AK Adresslistenaktualisierung,AK AK AK AK-Plan Programm,AK Arbeitszeiterfassung,AK Automatische Korrekturen,AK Awarenessarbeit,AK Berufungshandbuch,AK Datenschutz bei externer Software,AK Geschlechtergleichstellung,...,AK Prüfungsversuche,AK Kurier,AK KI im Studium,AK Evaluation,AK Akkreditierung,AK Plenumsleitung,AK Budget-Fahrten,AK Koma-Büro,AK Schlüsselkompetenzen und Nachhaltigkeit,Unnamed: 49
Fabian (Flexi),NaN,Nein,Nein,Nein,Nein,Nein,Unter Vorbehalt,Unter Vorbehalt,Nein,Unter Vorbehalt,...,Unter Vorbehalt,Nein,Unter Vorbehalt,Nein,Unter Vorbehalt,Nein,Nein,Nein,Unter Vorbehalt,NaN
Darline (Heidelberg),NaN,Nein,Nein,Nein,Nein,Nein,Nein,Ja,Nein,Nein,...,Unter Vorbehalt,Nein,Nein,Nein,Nein,Nein,Nein,Nein,Nein,NaN
Simon (Wien),NaN,Nein,Nein,Nein,Nein,Nein,Ja,Nein,Nein,Nein,...,Nein,Nein,Ja,Nein,Nein,Nein,Nein,Nein,Nein,NaN
Maxy (Hannover),NaN,Nein,Nein,Nein,Nein,Nein,Nein,Nein,Nein,Nein,...,Nein,Nein,Nein,Nein,Nein,Nein,Nein,Nein,Nein,NaN
Helen (Jena),NaN,Nein,Nein,Nein,Nein,Unter Vorbehalt,Unter Vorbehalt,Unter Vorbehalt,Nein,Nein,...,Unter Vorbehalt,Nein,Nein,Nein,Ja,Unter Vorbehalt,Ja,Nein,Nein,NaN

In [82]:
names = list(df.index)
assert len(names) == len(set(names))

ak_heads.difference(set(names))

In [79]:
with open("KoMa-test-meta.json", "r") as f:
    lp_in = json.load(f)

FileNotFoundError: [Errno 2] No such file or directory: 'KoMa-test-meta.json'

In [ ]:
ak_names = [col_name for col_name in df.columns if "Unnamed" not in col_name]
assert len(ak_names) == len(set(ak_names)), "duplicate ak names"
print(ak_names)
df

['Vereinssitzung KoMa e.V.', 'AK Adresslistenaktualisierung', 'AK AK AK AK-Plan Programm', 'AK Arbeitszeiterfassung', 'AK Automatische Korrekturen', 'AK Awarenessarbeit', 'AK Berufungshandbuch', 'AK Datenschutz bei externer Software', 'AK Geschlechtergleichstellung', 'AK Hygiene bei Veranstaltungen', 'AK IT-Infrastruktur', 'AK Kartenspielwerbung', 'AK Klausurtermine', 'AK Lehramt', 'AK Lehrkraftmangel', 'AK Mentoring', 'AK Nachteilsausgleiche', 'AK Online-Wahl', 'AK Social Media', 'AK Spiel &amp; Spaß', 'AK studentische Armut', 'AK TVStud', 'AK Veranstaltungen', 'AK WissZeitVG', 'AK Übungsleitungen', 'AK Studienwerbung', 'AK Zulassung zu Studiengängen', 'Ak Spendenveranstaltungen', 'AK Angabe von Symptonen bei krankheitsbedingten Prüfungsabmeldungen', 'AK Gendergerechte Toiletten', 'AK Datenschutz bei Fachschaftsarbeit', 'AK Vereine von Fachschaften und Nachwuchs in Vereinen', 'AK mental health', 'AK bundesweites Semesterticket', 'AK Meta', 'AK Orga', 'AK KoMa-Homepage-Inhalt', 'AK Ethikmodule', 'AK Umgang mit Fachschaftsbeef', 'AK Prüfungsversuche', 'AK Kurier', 'AK KI im Studium', 'AK Evaluation', 'AK Akkreditierung', 'AK Plenumsleitung', 'AK Budget-Fahrten', 'AK Koma-Büro', 'AK Schlüsselkompetenzen und Nachhaltigkeit']

,Unnamed: 0,Vereinssitzung KoMa e.V.,AK Adresslistenaktualisierung,AK AK AK AK-Plan Programm,AK Arbeitszeiterfassung,AK Automatische Korrekturen,AK Awarenessarbeit,AK Berufungshandbuch,AK Datenschutz bei externer Software,AK Geschlechtergleichstellung,...,AK Prüfungsversuche,AK Kurier,AK KI im Studium,AK Evaluation,AK Akkreditierung,AK Plenumsleitung,AK Budget-Fahrten,AK Koma-Büro,AK Schlüsselkompetenzen und Nachhaltigkeit,Unnamed: 49
Fabian (Flexi),NaN,Nein,Nein,Nein,Nein,Nein,Unter Vorbehalt,Unter Vorbehalt,Nein,Unter Vorbehalt,...,Unter Vorbehalt,Nein,Unter Vorbehalt,Nein,Unter Vorbehalt,Nein,Nein,Nein,Unter Vorbehalt,NaN
Darline (Heidelberg),NaN,Nein,Nein,Nein,Nein,Nein,Nein,Ja,Nein,Nein,...,Unter Vorbehalt,Nein,Nein,Nein,Nein,Nein,Nein,Nein,Nein,NaN
Simon(wien),NaN,Nein,Nein,Nein,Nein,Nein,Ja,Nein,Nein,Nein,...,Nein,Nein,Ja,Nein,Nein,Nein,Nein,Nein,Nein,NaN
Maxy (Hannover),NaN,Nein,Nein,Nein,Nein,Nein,Nein,Nein,Nein,Nein,...,Nein,Nein,Nein,Nein,Nein,Nein,Nein,Nein,Nein,NaN
Helen (Jena),NaN,Nein,Nein,Nein,Nein,Unter Vorbehalt,Unter Vorbehalt,Unter Vorbehalt,Nein,Nein,...,Unter Vorbehalt,Nein,Nein,Nein,Ja,Unter Vorbehalt,Ja,Nein,Nein,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Büsra (FAU Erlangen),NaN,Nein,Nein,Nein,Nein,Nein,Unter Vorbehalt,Nein,Ja,Unter Vorbehalt,...,Unter Vorbehalt,Unter Vorbehalt,Nein,Nein,Nein,Nein,Nein,Nein,Unter Vorbehalt,NaN
Max (TU Chemnitz),NaN,Nein,Nein,Nein,Unter Vorbehalt,Unter Vorbehalt,Unter Vorbehalt,Nein,Nein,Nein,...,Nein,Nein,Nein,Nein,Nein,Nein,Unter Vorbehalt,Nein,Nein,NaN
Alicia (TU Chemnitz),NaN,Nein,Nein,Nein,Unter Vorbehalt,Unter Vorbehalt,Unter Vorbehalt,Nein,Nein,Unter Vorbehalt,...,Nein,Nein,Nein,Nein,Nein,Nein,Unter Vorbehalt,Nein,Nein,NaN
Caroline (Erlangen),NaN,Nein,Nein,Nein,Nein,Nein,Unter Vorbehalt,Ja,Nein,Nein,...,Unter Vorbehalt,Nein,Unter Vorbehalt,Nein,Nein,Nein,Nein,Nein,Ja,NaN
"Tim (alterSack, Bonn - nicht da höchstens Samstag)",NaN,Nein,Nein,Ja,Nein,Nein,Nein,Nein,Nein,Nein,...,Nein,Nein,Nein,Nein,Nein,Nein,Nein,Nein,Nein,NaN

In [ ]:
ak_name_to_id_dict = {ak['info']['name']: ak['id'] for ak in lp_in['aks']}
part_name_to_id_dict = {part['info']['name']: part['id'] for part in lp_in['participants']}
print(ak_name_to_id_dict)

NameError: name 'lp_in' is not defined

In [ ]:
def calc_pref_score(entry: str) -> int:
    if entry in ["Nein", "No"]:
        return 0
    elif entry in ["Ja", "Yes"]:
        return 2
    elif entry in ["Unter Vorbehalt", "Under reserve"]:
        return 1
    else:
        raise NotImplementedError
        
def get_part_dict(entries):
    name = entries.name
    if name in part_name_to_id_dict:
        return lp_in['participants'][part_name_to_id_dict[name]]
    i = 0
    while f"participant{i}" in part_name_to_id_dict.values():
        i+=1
    part_id = f"participant{i}"
    part_name_to_id_dict[part_id] = name
    participant_dict = {
        "id": part_id,
        "info": {"name": name},
        "time_constraints": [],
        "room_constraints": [],
        "preferences": [],
    }
    return participant_dict

In [ ]:
result_dict = lp_in

index_lst = []
for idx, entries in df.iterrows():
    
    participant_dict = get_part_dict(entries)

    for ak_name in ak_names:
        score = calc_pref_score(entries[ak_name])
        if score != 0:
            participant_dict["preferences"].append(
                {
                    "ak_id": ak_name_to_id_dict[ak_name],
                    "required": False,
                    "preference_score": score,
                }
            )
    if not participant_dict["preferences"]:
        continue
    result_dict["participants"].append(participant_dict)
    index_lst.append(idx)

assert len(index_lst) == len(set(index_lst)), "duplicate participant names"

In [ ]:
result_dict

{'rooms': [{'id': 'room0',
   'info': {'name': 'Raum 0.003'},
   'capacity': 3,
   'fulfilled_room_constraints': ['Beamer'],
   'time_constraints': ['room0.003']},
  {'id': 'room1',
   'info': {'name': 'Raum 0.008'},
   'capacity': 6,
   'fulfilled_room_constraints': ['Tafel', 'Beamer'],
   'time_constraints': ['room0.008']},
  {'id': 'room2',
   'info': {'name': 'Zeichensaal'},
   'capacity': 10,
   'fulfilled_room_constraints': ['Tafel'],
   'time_constraints': ['Zeichensaal']}],
 'timeslots': {'info': {'duration': '2 hour blocks'},
  'blocks': [[{'id': 'timeslot0',
     'info': {'start': 'Donnerstag 8:00'},
     'fulfilled_time_constraints': ['Reso',
      'room0.003',
      'room0.008',
      'Zeichensaal',
      'ak02',
      'ak06']},
    {'id': 'timeslot1',
     'info': {'start': 'Donnerstag 10:00'},
     'fulfilled_time_constraints': ['Reso',
      'room0.003',
      'room0.008',
      'Zeichensaal',
      'ak02']}],
   [{'id': 'timeslot2',
     'info': {'start': 'Freitag 14:00'},
     'fulfilled_time_constraints': ['Reso',
      'room0.003',
      'Zeichensaal',
      'ak02',
      'ak06']},
    {'id': 'timeslot3',
     'info': {'start': 'Freitag 16:00'},
     'fulfilled_time_constraints': ['Reso',
      'room0.003',
      'Zeichensaal',
      'ak02',
      'ak06']}],
   [{'id': 'timeslot4',
     'info': {'start': 'Samstag 08:00'},
     'fulfilled_time_constraints': ['room0.003',
      'room0.008',
      'Zeichensaal',
      'ak02',
      'ak06']},
    {'id': 'timeslot5',
     'info': {'start': 'Samstag 10:00'},
     'fulfilled_time_constraints': ['room0.003',
      'room0.008',
      'Zeichensaal']}]]},
 'aks': [{'id': 'ak00',
   'duration': 1,
   'properties': {},
   'room_constraints': [],
   'time_constraints': [],
   'info': {'name': 'AK KoMa',
    'head': 'N/A',
    'description': 'N/A',
    'reso': False}},
  {'id': 'ak01',
   'duration': 1,
   'properties': {},
   'room_constraints': ['Beamer'],
   'time_constraints': [],
   'info': {'name': 'AK Website',
    'head': 'N/A',
    'description': 'N/A',
    'reso': False}},
  {'id': 'ak02',
   'duration': 1,
   'properties': {},
   'room_constraints': ['Beamer'],
   'time_constraints': ['ak02'],
   'info': {'name': 'AK BMBF',
    'head': 'N/A',
    'description': 'N/A',
    'reso': False}},
  {'id': 'ak03',
   'duration': 1,
   'properties': {},
   'room_constraints': ['Beamer', 'Tafel'],
   'time_constraints': [],
   'info': {'name': 'AK Advent',
    'head': 'N/A',
    'description': 'N/A',
    'reso': False}},
  {'id': 'ak04',
   'duration': 1,
   'properties': {},
   'room_constraints': ['Beamer'],
   'time_constraints': [],
   'info': {'name': 'AK Minimalstandard',
    'head': 'N/A',
    'description': 'N/A',
    'reso': False}},
  {'id': 'ak05',
   'duration': 1,
   'properties': {},
   'room_constraints': [],
   'time_constraints': [],
   'info': {'name': 'AK KdV',
    'head': 'N/A',
    'description': 'N/A',
    'reso': False}},
  {'id': 'ak06',
   'duration': 1,
   'properties': {},
   'room_constraints': [],
   'time_constraints': ['ak06'],
   'info': {'name': 'AK Handzeichen',
    'head': 'N/A',
    'description': 'N/A',
    'reso': False}},
  {'id': 'ak07',
   'duration': 1,
   'properties': {},
   'room_constraints': [],
   'time_constraints': [],
   'info': {'name': 'AK Pella',
    'head': 'N/A',
    'description': 'N/A',
    'reso': False}},
  {'id': 'ak08',
   'duration': 1,
   'properties': {},
   'room_constraints': ['Tafel'],
   'time_constraints': ['Reso'],
   'info': {'name': 'AK Grundausstattung',
    'head': 'N/A',
    'description': 'N/A',
    'reso': True}},
  {'id': 'ak09',
   'duration': 1,
   'properties': {},
   'room_constraints': [],
   'time_constraints': ['Reso'],
   'info': {'name': 'AK Onlinewahlen',
    'head': 'N/A',
    'description': 'N/A',
    'reso': True}},
  {'id': 'ak10',
   'duration': 1,
   'properties': {},
   'room_constraints': ['Beamer'],
   'time_constraints': ['Reso'],
   'info': {'name': 'AK CHE',
    'head': 'N/A',
    'description': 'N/A',
    'reso': True}},
  {'id': 'ak11',
   'duration': 1,
   'properties': {},
   'room_constraints': [],
   'time_constraints': ['Reso'],
   'info': {'name': 'AK Taschenrechner',
    'head': 'N/A',
    'description': 'N/A',
    'reso': True}},
  {'id': 'ak12',
   'duration': 1,
   'properties': {},
   'room_constraints': [],
   'time_constraints': ['Reso'],
   'info': {'name': 'ak1', 'head': 'N/A', 'description': 'N/A', 'reso': True}},
  {'id': 'ak13',
   'duration': 1,
   'properties': {},
   'room_constraints': [],
   'time_constraints': ['Reso'],
   'info': {'name': 'ak2',
    'head': 'N/A',
    'description': 'N/A',
    'reso': True}}],
 'participants': [{'id': 'participant0',
   'info': {'name': 'Alice'},
   'preferences': [{'ak_id': 'ak00', 'required': False, 'preference_score': 1},
    {'ak_id': 'ak01', 'required': True, 'preference_score': -1},
    {'ak_id': 'ak04', 'required': False, 'preference_score': 1},
    {'ak_id': 'ak05', 'required': False, 'preference_score': 1},
    {'ak_id': 'ak08', 'required': False, 'preference_score': 1},
    {'ak_id': 'ak09', 'required': False, 'preference_score': 1},
    {'ak_id': 'ak11', 'required': False, 'preference_score': 1}],
   'room_constraints': [],
   'time_constraints': []},
  {'id': 'participant1',
   'info': {'name': 'Bob'},
   'preferences': [{'ak_id': 'ak08', 'required': True, 'preference_score': -1},
    {'ak_id': 'ak09', 'required': True, 'preference_score': -1},
    {'ak_id': 'ak10', 'required': False, 'preference_score': 1},
    {'ak_id': 'ak11', 'required': False, 'preference_score': 1}],
   'room_constraints': [],
   'time_constraints': []},
  {'id': 'participant2',
   'info': {'name': 'Claire'},
   'preferences': [{'ak_id': 'ak00', 'required': False, 'preference_score': 1},
    {'ak_id': 'ak01', 'required': False, 'preference_score': 1},
    {'ak_id': 'ak02', 'required': False, 'preference_score': 1},
    {'ak_id': 'ak03', 'required': False, 'preference_score': 1},
    {'ak_id': 'ak04', 'required': False, 'preference_score': 1}],
   'room_constraints': [],
   'time_constraints': []},
  {'id': 'participant3',
   'info': {'name': 'David'},
   'preferences': [{'ak_id': 'ak05', 'required': False, 'preference_score': 1},
    {'ak_id': 'ak07', 'required': False, 'preference_score': 1},
    {'ak_id': 'ak10', 'required': True, 'preference_score': -1}],
   'room_constraints': [],
   'time_constraints': []},
  {'id': 'participant4',
   'info': {'name': 'Emil'},
   'preferences': [{'ak_id': 'ak06', 'required': False, 'preference_score': 1},
    {'ak_id': 'ak07', 'required': False, 'preference_score': 1},
    {'ak_id': 'ak09', 'required': False, 'preference_score': 1}],
   'room_constraints': [],
   'time_constraints': []},
  {'id': 'participant5',
   'info': {'name': 'Fried'},
   'preferences': [{'ak_id': 'ak00', 'required': True, 'preference_score': -1},
    {'ak_id': 'ak02', 'required': False, 'preference_score': 1},
    {'ak_id': 'ak04', 'required': True, 'preference_score': -1},
    {'ak_id': 'ak06', 'required': False, 'preference_score': 1},
    {'ak_id': 'ak07', 'required': False, 'preference_score': 1},
    {'ak_id': 'ak08', 'required': False, 'preference_score': 1},
    {'ak_id': 'ak09', 'required': False, 'preference_score': 1}],
   'room_constraints': [],
   'time_constraints': []},
  {'id': 'participant6',
   'info': {'name': 'Gerti'},
   'preferences': [{'ak_id': 'ak00', 'required': False, 'preference_score': 1},
    {'ak_id': 'ak02', 'required': False, 'preference_score': 1},
    {'ak_id': 'ak04', 'required': False, 'preference_score': 1},
    {'ak_id': 'ak06', 'required': False, 'preference_score': 1},
    {'ak_id': 'ak08', 'required': False, 'preference_score': 1},
    {'ak_id': 'ak10', 'required': False, 'preference_score': 1}],
   'room_constraints': [],
   'time_constraints': []},
  {'id': 'participant7',
   'info': {'name': 'Hans'},
   'preferences': [{'ak_id': 'ak00', 'required': False, 'preference_score': 1},
    {'ak_id': 'ak03', 'required': False, 'preference_score': 1},
    {'ak_id': 'ak06', 'required': False, 'preference_score': 1},
    {'ak_id': 'ak09', 'required': False, 'preference_score': 1}],
   'room_constraints': [],
   'time_constraints': []},
  {'id': 'participant8',
   'info': {},
   'time_constraints': [],
   'room_constraints': [],
   'preferences': [{'ak_id': 'ak12', 'required': False, 'preference_score': 2},
    {'ak_id': 'ak13', 'required': False, 'preference_score': 1}]},
  {'id': 'participant8',
   'info': {},
   'time_constraints': [],
   'room_constraints': [],
   'preferences': [{'ak_id': 'ak12', 'required': False, 'preference_score': 2},
    {'ak_id': 'ak13', 'required': False, 'preference_score': 2}]},
  {'id': 'participant8',
   'info': {},
   'time_constraints': [],
   'room_constraints': [],
   'preferences': [{'ak_id': 'ak13',
     'required': False,
     'preference_score': 1}]},
  {'id': 'participant8',
   'info': {},
   'time_constraints': [],
   'room_constraints': [],
   'preferences': [{'ak_id': 'ak12', 'required': False, 'preference_score': 2},
    {'ak_id': 'ak13', 'required': False, 'preference_score': 1}]},
  {'id': 'participant8',
   'info': {},
   'time_constraints': [],
   'room_constraints': [],
   'preferences': [{'ak_id': 'ak12', 'required': False, 'preference_score': 2},
    {'ak_id': 'ak13', 'required': False, 'preference_score': 2}]},
  {'id': 'participant8',
   'info': {},
   'time_constraints': [],
   'room_constraints': [],
   'preferences': [{'ak_id': 'ak13',
     'required': False,
     'preference_score': 1}]},
  {'id': 'participant8',
   'info': {'name': 'Test'},
   'time_constraints': [],
   'room_constraints': [],
   'preferences': [{'ak_id': 'ak12', 'required': False, 'preference_score': 2},
    {'ak_id': 'ak13', 'required': False, 'preference_score': 1}]},
  {'id': 'participant8',
   'info': {'name': 'noch jemand'},
   'time_constraints': [],
   'room_constraints': [],
   'preferences': [{'ak_id': 'ak12', 'required': False, 'preference_score': 2},
    {'ak_id': 'ak13', 'required': False, 'preference_score': 2}]},
  {'id': 'participant8',
   'info': {'name': 'ein kömischer Name'},
   'time_constraints': [],
   'room_constraints': [],
   'preferences': [{'ak_id': 'ak13',
     'required': False,
     'preference_score': 1}]}],
 'info': {'name': 'First example from the legacy code base',
  'author': 'Tim Racs'}}

In [ ]:
with open("export.json", "w") as f:
    json.dump(result_dict, f, indent=4)